---
title: "still_no_clue"
author: "Mike"
date: "3/5/2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
set.seed = 12321

# Linear model w/ one with a continuous predictor variable and a continous response variable
# The relationship described by a single parameter, B1 (slope, sand consequently a predictor of effect size)
predictor <- runif(100) - 0.5  ## a uniformly distributed random number between -0.5 and 0.5
B0 <- 1
B1 <- 3
response <- B0 + B1 * predictor
```

```{r}

gen.mod <- function(n = 100, b0 = 2, b1 = 3, sd.err = 1) {
  predictor <- runif(n) - 0.5
  response <- b0 + b1 * predictor + rnorm(n, mean = 0, sd = sd.err)
  return(data.frame(response = response, predictor = predictor))
}
```




```{r, echo=TRUE}
n.times <- 1000
est.df <- matrix(nrow = n.times, ncol = 5, NA)
for (i in 1:n.times) {
  m1 <- lm(response ~ predictor, data = gen.mod(n = 100, b0 = 1, b1 = 3, sd.err = 1))
  est.df[i, 1] <- summary(m1)$coefficients["predictor", "Estimate"]
  m1 <- lm(response ~ predictor, data = gen.mod(n = 100, b0 = 1, b1 = 3, sd.err = 5))
  est.df[i, 2] <- summary(m1)$coefficients["predictor", "Estimate"]
  m1 <- lm(response ~ predictor, data = gen.mod(n = 100, b0 = 1, b1 = 3, sd.err = 10))
  est.df[i, 3] <- summary(m1)$coefficients["predictor", "Estimate"]
  m1 <- lm(response ~ predictor, data = gen.mod(n = 100, b0 = 1, b1 = 3, sd.err = 15))
  est.df[i, 4] <- summary(m1)$coefficients["predictor", "Estimate"]
  m1 <- lm(response ~ predictor, data = gen.mod(n = 100, b0 = 1, b1 = 3, sd.err = 20))
  est.df[i, 5] <- summary(m1)$coefficients["predictor", "Estimate"]
}
est.df <- data.frame(est.df)

## split est.df into a data frame in long format
est.df <- gather(est.df, value = "est", key="trial")
est.df$trial <- factor(est.df$trial)

est.sum.df <- group_by(est.df, trial) %>% summarize(mn.est = mean(est))

p <- ggplot(aes(est, group = trial, col = trial), data = est.df)
p + geom_density() + geom_vline(data = est.sum.df, aes(xintercept = mn.est, col = trial))

```



```{r, echo=TRUE}
n.times <- 1000
est.df <- matrix(nrow = n.times, ncol = 5, NA)
for (i in 1:n.times) {
  m1 <- lm(response ~ predictor, data = gen.mod(n = 100, b0 = 1, b1 = 1, sd.err = 1))
  est.df[i, 1] <- summary(m1)$coefficients["predictor", "Estimate"]
  m1 <- lm(response ~ predictor, data = gen.mod(n = 100, b0 = 1, b1 = 6, sd.err = 1))
  est.df[i, 2] <- summary(m1)$coefficients["predictor", "Estimate"]
  m1 <- lm(response ~ predictor, data = gen.mod(n = 100, b0 = 1, b1 = 21, sd.err = 1))
  est.df[i, 3] <- summary(m1)$coefficients["predictor", "Estimate"]
  m1 <- lm(response ~ predictor, data = gen.mod(n = 100, b0 = 1, b1 = 48, sd.err = 1))
  est.df[i, 4] <- summary(m1)$coefficients["predictor", "Estimate"]
  m1 <- lm(response ~ predictor, data = gen.mod(n = 100, b0 = 1, b1 = 81, sd.err = 1))
  est.df[i, 5] <- summary(m1)$coefficients["predictor", "Estimate"]
}
est.df <- data.frame(est.df)

## split est.df into a data frame in long format
est.df <- gather(est.df, value = "est", key="trial")
est.df$trial <- factor(est.df$trial)

est.sum.df <- group_by(est.df, trial) %>% summarize(mn.est = mean(est))

p <- ggplot(aes(est, group = trial, col = trial), data = est.df)
p + geom_density() + geom_vline(data = est.sum.df, aes(xintercept = mn.est, col = trial))

# ANGRY 
```


```{r, echo=TRUE}
n.times <- 1000
est.df <- matrix(nrow = n.times, ncol = 5, NA)
for (i in 1:n.times) {
  m1 <- lm(response ~ predictor, data = gen.mod(n = 10, b0 = 1, b1 = 1, sd.err = 1))
  est.df[i, 1] <- summary(m1)$coefficients["predictor", "Estimate"]
  m1 <- lm(response ~ predictor, data = gen.mod(n = 50, b0 = 1, b1 = 1, sd.err = 1))
  est.df[i, 2] <- summary(m1)$coefficients["predictor", "Estimate"]
  m1 <- lm(response ~ predictor, data = gen.mod(n = 100, b0 = 1, b1 = 1, sd.err = 1))
  est.df[i, 3] <- summary(m1)$coefficients["predictor", "Estimate"]
  m1 <- lm(response ~ predictor, data = gen.mod(n = 500, b0 = 1, b1 = 1, sd.err = 1))
  est.df[i, 4] <- summary(m1)$coefficients["predictor", "Estimate"]
  m1 <- lm(response ~ predictor, data = gen.mod(n = 1000, b0 = 1, b1 = 1, sd.err = 1))
  est.df[i, 5] <- summary(m1)$coefficients["predictor", "Estimate"]
}
est.df <- data.frame(est.df)

## split est.df into a data frame in long format
est.df <- gather(est.df, value = "est", key="trial")
est.df$trial <- factor(est.df$trial)

est.sum.df <- group_by(est.df, trial) %>% summarize(mn.est = mean(est))

p <- ggplot(aes(est, group = trial, col = trial), data = est.df)
p + geom_density() + geom_vline(data = est.sum.df, aes(xintercept = mn.est, col = trial))

```



